service:
  name: connect-vanity-handler
  runtime: nodejs22.x
  handler: src/handler.main
  timeout: 10
  memory_size: 256
  log_retention_days: 14
  source_dir: dist/src
  environment:
    TABLE_NAME: ${DYNAMODB_TABLE_NAME}
  role:
    create: true
    name: connect-vanity-handler-role
    policy_name: connect-vanity-handler-policy
    statements:
      - effect: Allow
        actions:
          - dynamodb:PutItem
        resources:
          - ${DYNAMODB_TABLE_ARN}

trigger:
  type: aws-connect
